name: test_project
description: "A new Flutter project."

publish_to: 'none' # Remarque : Cela empêche la publication sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  http: ^0.13.5
  crypto: ^3.0.0
  flutter_local_notifications: ^9.2.0
  supabase_flutter: ^1.0.0
  cloud_firestore: ^4.17.5
  socket_io_client: ^2.0.0
  fluttertoast: ^8.0.9  # Ajoutez cette ligne
  # firebase_storage: ^x.x.x # Décommentez si vous utilisez Firebase Storage
  cupertino_icons: ^1.0.8
  image_gallery_saver: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile.jpg
