// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqAlzBGklnMc1EwpFCEvNWLyBFDkIf64o',
    appId: '1:765790719322:web:74a50af558fe1f75a77763',
    messagingSenderId: '765790719322',
    projectId: 'ppitest-8dd92',
    authDomain: 'ppitest-8dd92.firebaseapp.com',
    storageBucket: 'ppitest-8dd92.appspot.com',
    measurementId: 'G-E7SVNTMH9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkdcelM3Yi6i7WqMkKC9xH6gNjc1j1eco',
    appId: '1:765790719322:android:481e17fadf9af6faa77763',
    messagingSenderId: '765790719322',
    projectId: 'ppitest-8dd92',
    storageBucket: 'ppitest-8dd92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5f5Z-f1jJ1U1qFEqpWZ4e5Vuk1jVT5xI',
    appId: '1:765790719322:ios:98816325fcf8cb08a77763',
    messagingSenderId: '765790719322',
    projectId: 'ppitest-8dd92',
    storageBucket: 'ppitest-8dd92.appspot.com',
    iosBundleId: 'com.example.testPrj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5f5Z-f1jJ1U1qFEqpWZ4e5Vuk1jVT5xI',
    appId: '1:765790719322:ios:98816325fcf8cb08a77763',
    messagingSenderId: '765790719322',
    projectId: 'ppitest-8dd92',
    storageBucket: 'ppitest-8dd92.appspot.com',
    iosBundleId: 'com.example.testPrj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqAlzBGklnMc1EwpFCEvNWLyBFDkIf64o',
    appId: '1:765790719322:web:5b6fbfd8d87f8a20a77763',
    messagingSenderId: '765790719322',
    projectId: 'ppitest-8dd92',
    authDomain: 'ppitest-8dd92.firebaseapp.com',
    storageBucket: 'ppitest-8dd92.appspot.com',
    measurementId: 'G-176B6EZ6KR',
  );
}
